import { describe, it } from 'node:test';
import assert from 'node:assert/strict';
import { generateManifest, generateIcon, generateServiceWorker, injectPWA, packageAsStandalone } from '../lib/export/packager.js';
import { writeFileSync, mkdirSync, readFileSync, rmSync } from 'node:fs';
import { join } from 'node:path';

const TMP = join(import.meta.dirname, '..', '.test-tmp-packager');

describe('Packager', () => {
  it('generates valid manifest', () => {
    const m = generateManifest({ name: 'Test App', emoji: '🧪' });
    assert.equal(m.name, 'Test App');
    assert.equal(m.display, 'standalone');
    assert.equal(m.start_url, './index.html');
    assert.ok(m.icons[0].src.includes('%F0%9F%A7%AA')); // encoded 🧪
  });

  it('generates SVG icon', () => {
    const svg = generateIcon('⚡');
    assert.ok(svg.includes('<svg'));
    assert.ok(svg.includes('⚡'));
  });

  it('generates service worker', () => {
    const sw = generateServiceWorker('test-cache-v1');
    assert.ok(sw.includes("const CACHE = 'test-cache-v1'"));
    assert.ok(sw.includes('skipWaiting'));
    assert.ok(sw.includes('caches.match'));
  });

  it('injects PWA into HTML with head', () => {
    const html = '<html><head><title>T</title></head><body></body></html>';
    const result = injectPWA(html);
    assert.ok(result.includes('manifest.json'));
    assert.ok(result.includes('serviceWorker'));
    assert.ok(result.includes('</head>'));
  });

  it('injects PWA into HTML without head', () => {
    const html = '<div>Hello</div>';
    const result = injectPWA(html);
    assert.ok(result.includes('manifest.json'));
  });

  it('packages as standalone', () => {
    mkdirSync(TMP, { recursive: true });
    const src = join(TMP, 'source.html');
    writeFileSync(src, '<html><head></head><body><h1>Hi</h1></body></html>');
    
    const out = join(TMP, 'standalone.html');
    const result = packageAsStandalone(src, out);
    assert.ok(result.path === out);
    assert.ok(result.size > 0);
    
    const content = readFileSync(out, 'utf-8');
    assert.ok(content.includes('Generated by MODUS Forge'));
    assert.ok(content.includes('viewport'));
    
    rmSync(TMP, { recursive: true, force: true });
  });
});
